import { z } from "zod";
import { tool } from "@langchain/core/tools";
import { simpleGit } from "simple-git";
import { Octokit } from "@octokit/rest";
import { join } from "node:path";
import type { AiAgentEnv, HealJobPayload } from "@g-heal-claw/shared";
import { renderPrBody } from "../git/pr-template.js";

/**
 * createPr — 提交 patch 分支并创建 GitHub PR
 */
export function createCreatePrTool(payload: HealJobPayload, env: AiAgentEnv) {
  return tool(
    async ({ title, diagnosis, confidence }) => {
      const repoDir = getRepoDir(payload.healJobId);
      const branchName = `ghc-heal/${payload.healJobId}`;

      try {
        const git = simpleGit(repoDir);

        // 创建修复分支
        await git.checkoutLocalBranch(branchName);
        await git.add(".");
        await git.commit(`fix: ${title}\n\nAuto-generated by g-heal-claw AI Agent\nIssue: ${payload.issueId}`);
        await git.push("origin", branchName, ["--set-upstream"]);

        // 创建 PR
        const { owner, repo } = parseGitHubUrl(payload.repoUrl);
        const octokit = createOctokit(env);

        const body = renderPrBody({
          issueId: payload.issueId,
          issueTitle: payload.issueTitle,
          diagnosis,
          confidence,
          healJobId: payload.healJobId,
        });

        const { data: pr } = await octokit.pulls.create({
          owner,
          repo,
          title: `fix: ${title}`,
          body,
          head: branchName,
          base: payload.branch,
          draft: false,
        });

        // 添加标签
        await octokit.issues.addLabels({
          owner,
          repo,
          issue_number: pr.number,
          labels: ["ai-heal", "auto-generated"],
        });

        return `PR created: ${pr.html_url}`;
      } catch (err) {
        return `ERROR: Failed to create PR — ${err instanceof Error ? err.message : String(err)}`;
      }
    },
    {
      name: "createPr",
      description: "将修复提交推送到新分支并创建 GitHub Pull Request",
      schema: z.object({
        title: z.string().describe("PR 标题（简短描述修复内容）"),
        diagnosis: z.string().describe("诊断摘要（根因分析）"),
        confidence: z.enum(["high", "medium", "low"]).describe("修复置信度"),
      }),
    },
  );
}

function createOctokit(env: AiAgentEnv): Octokit {
  // MVP: 使用 GitHub App private key 获取 installation token
  // 简化实现：如果有 GITHUB_APP_ID + PRIVATE_KEY 用 App auth，否则 fallback 到 PAT
  const token = env.GITHUB_APP_PRIVATE_KEY_PATH || "";
  return new Octokit({ auth: token });
}

function parseGitHubUrl(repoUrl: string): { owner: string; repo: string } {
  // 支持 https://github.com/owner/repo.git 和 git@github.com:owner/repo.git
  const httpsMatch = repoUrl.match(/github\.com\/([^/]+)\/([^/.]+)/);
  if (httpsMatch) return { owner: httpsMatch[1], repo: httpsMatch[2] };

  const sshMatch = repoUrl.match(/github\.com:([^/]+)\/([^/.]+)/);
  if (sshMatch) return { owner: sshMatch[1], repo: sshMatch[2] };

  throw new Error(`Cannot parse GitHub owner/repo from URL: ${repoUrl}`);
}

function getRepoDir(healJobId: string): string {
  return join(process.env.TMPDIR ?? "/tmp", "ghc-heal", healJobId);
}
